### ISSUE TITLE
Exceptions in current release

### ISSUE THREAD

**Issue by Johndirr** [protyposis/Aurio#11]
I just tried the newest release by running the Aurio.Test.FingerprintingHaitsmaKalker2002 project. It gives me the following exeption on any file I throw at it:
"NotSupportedException: Cannot create instance because no factory has been set."

Ignoring the previous exception I also get the following Exception when the wav file gets written:
"Invalid WAV file - No fmt chunk found"

Any idea whats wrong here?

**Comment by protyposis** [comment]
The exception happened because the app did not set the FFT and resampling factories. Should be fixed now.
