### ISSUE TITLE
[SUGGESTION] More resamplers, more fun

### ISSUE THREAD

**Issue by forart** [protyposis/Aurio#19]
Since the latest version updated some resamplers included (Soxr), it would be very useful to have more algorithms to let users choose their favourite/needed one...
...here's some - known - examples:
- @avaneev's [r8brain-free-src](https://github.com/avaneev/r8brain-free-src#r8brain-free-src---high-quality-fast-resampler-in-c) (high-quality professional audio sample rate converter (SRC) / resampler C++ library);
- @delude88's/@Lwnzhn's [zita-resampler](https://github.com/digital-stage/zita-resampler#zita-resampler) (library for resampling audio signals designed to be used in real-time);
- @levmin's [SRDoubler](https://github.com/levmin/SRDoubler#readme) (high-fidelity bandlimited interpolation sampling rate doubler).

There are of course some interesting "approaches" to resampling that may inspire such as:
- @jniemann66's [ReSampler](https://github.com/jniemann66/ReSampler#synopsis) (high quality command-line audio sample rate converter);
- @unevens's [Oversimple](https://github.com/unevens/oversimple#oversimple) (wraps two of the best resampling libraries available)

Please consider that [hydrogenaudio](https://hydrogenaud.io/) is the place to ask/discuss/post about this (and other digital-audio related) topic too.

Last but not least, as always, check out our [AUDIO](https://github.com/forart/HyMPS#-) \ [Tools page](https://github.com/forart/HyMPS/blob/main/A_Tools.md#subsections) for other - maybe - inspiring algos to add...

**Comment by protyposis** [comment]
Thank you, but there is currently no reason to add additional resamplers (or FFTs).
