### ISSUE TITLE
FFmpeg 2.8.2 is now missing from the website

### ISSUE THREAD

**Issue by keenua** [protyposis/Aurio#2]
I'm struggling to find FFmpeg 2.8.2 builds for any of the configurations (dev/shared/win32/win64) anywhere. They seem to have removed it completely even from the archive.

Do you happen to have a backup of those libraries stored somewhere?
Aurio fails to build with latest version of FFmpeg.

(Thanks in advance!)

**Comment by Medisex64** [comment]
Lucky for you, I do have a backup of them stored on my computer. Get them from here:
https://drive.google.com/open?id=0BwdwaAIDwZiyN3BOT0g5akM4eXM

I also put the auto extractor bat file. Needs 7zip in advance.

**Comment by keenua** [comment]
Oh, the pleasure of seeing "Rebuild All succeeded" :)

Thanks a lot, worked like a charm!

**Comment by protyposis** [comment]
FFmpeg has been updated to 3.3.3.
