### ISSUE TITLE
SQLite storage broken

### ISSUE THREAD

**Issue by QsmQls** [protyposis/Aurio#3]
Dear all,

Finally, the software is compiled without problems and issues like the one I described in previous issue. 

Now I would like to excute the program and save the db structure at the local machine disc instead of the memory as it was in the code. That is done by using SQLite. So, the problem can be described in the subsequent code lines. 

Here is a piece of code:
//db = new SQLiteConnection(":memory:");   --> this works
db = new SQLiteConnection("Data Source=C:\\test.sqlite"); ---> This does not work ... file not found

Even when I tried to create automatically the file I could not find the method SQLiteConnection.Createfile.

Please, can you give any advice or help on the source of this error encountered and how possibly could be resolved.

Thanks in advance

**Comment by protyposis** [comment]
Storing to SQLite is currently broken but can be fixed easily:

 * Open `SQLiteWinInterop.cs` and replace the strings `"mysql3.x86.dll"` with `"sqlite3.x86.dll"` and `"mysql3.x64.dll"` with `"sqlite3.x64.dll"`
 * Copy the files `sqlite3.x86.dll` and `sqlite3.x64.dll` to the output directory (where `Aurio.dll`/`SQLite_Net.dll` are)
 * Correctly specify the path the the SQLite file (`db = new SQLiteConnection(".\\test.sqlite");`; without `Data Source=`) in a directory where you have write access (`C:\` is usually write protected and won't work; e.g. specifying the current working directory will work `".\\test.sqlite"`)

**Comment by QsmQls** [comment]
Thank you

**Comment by protyposis** [comment]
Issues are fixed in newest version.
