### ISSUE TITLE
Can I apply the fingerprint matching algorithm for speech recognition purposes?

### ISSUE THREAD

**Issue by ohsorry** [protyposis/Aurio#4]
i have a lot of human voice recordings. I want to count the occurrences of special words or phrases in the recordings.
How can i achieve it? customize the FingerprintGenerator's profile?

**Comment by protyposis** [comment]
Audio fingerprinting is designed to find copies of the same audio; even when the same person says the same word two times, it's already different and extremely hard to detect with fingerprinting... if a word is said by different persons it's already so different that fingerprinting won't detect it at all. So the answer is unfortunately that this is not going to work, you'll have to look into actual speech recognition.

**Comment by ohsorry** [comment]
Oh,i see.sorry to hear that. thanks a lot :）
