### ISSUE TITLE
Automated script to use match and align 

### ISSUE THREAD

**Issue by BorisMolch** [protyposis/Aurio#7]
Hello!
It is not a real issue per say but I am looking for a way to use the match and align function in an automated script that processes multiple files and edits certain parts out.
I dont know C# , and write my script in python.
I have been looking into ways I can use the Aurio library via IronPython or Python for .Net
Any tips on how this can be done ? 
Not sure what I need to import to python, or if this is even possible. 
Thank you !

**Comment by protyposis** [comment]
I am sure it is possible with both Python variants but I don't have any experience with them so I'm not able to help here.
